import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Clock, Target, Award, FolderGit2, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import Layout from '@/components/layout/Layout';
import { Button } from '@/components/ui/button';

interface RoadmapPhase {
  phase: string;
  duration: string;
  title: string;
  skills: string[];
  certifications: string[];
  projects: string[];
}

const RoadmapsPage = () => {
  const [roadmapPhases, setRoadmapPhases] = useState<RoadmapPhase[]>([]);

  useEffect(() => {
    const stored = localStorage.getItem('careerverse_generated_roadmap');
    if (stored) {
      try {
        const parsed = JSON.parse(stored);
        if (Array.isArray(parsed)) setRoadmapPhases(parsed);
      } catch {}
    }
  }, []);

  const hasRoadmap = roadmapPhases.length > 0;

  return (
    <Layout>
      <div className="section-container py-12">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="text-center mb-12"
        >
          <h1 className="text-4xl sm:text-5xl font-bold mb-4">
            Your <span className="gradient-text">Learning Roadmap</span>
          </h1>
          <p className="text-muted-foreground max-w-2xl mx-auto text-lg">
            {hasRoadmap
              ? 'Your personalized career roadmap, generated by AI'
              : 'Generate a personalized roadmap to see it here'}
          </p>
        </motion.div>

        {!hasRoadmap ? (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="glass-card p-12 max-w-2xl mx-auto text-center"
          >
            <Sparkles className="w-12 h-12 text-primary mx-auto mb-4 opacity-60" />
            <h3 className="text-xl font-bold mb-2">No Roadmap Yet</h3>
            <p className="text-muted-foreground mb-6">
              Generate a roadmap to see it here.
            </p>
            <Link to="/roadmap-generator">
              <Button className="glow-button text-white border-0">
                <Sparkles className="w-4 h-4 mr-2" />
                Generate Your Roadmap
              </Button>
            </Link>
          </motion.div>
        ) : (
          <div className="max-w-3xl mx-auto">
            <div className="relative pl-8 sm:pl-12">
              {/* Dotted vertical line */}
              <div className="absolute left-[15px] sm:left-[23px] top-0 bottom-0 w-px border-l-2 border-dashed border-primary/40" />

              <div className="space-y-10">
                {roadmapPhases.map((phase, index) => (
                  <motion.div
                    key={phase.phase + index}
                    initial={{ opacity: 0, x: -30 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.15 + index * 0.12, duration: 0.5 }}
                    className="relative"
                  >
                    {/* Timeline dot */}
                    <div className="absolute -left-8 sm:-left-12 top-1">
                      <motion.div
                        initial={{ scale: 0 }}
                        animate={{ scale: 1 }}
                        transition={{ delay: 0.3 + index * 0.12, type: 'spring', stiffness: 300 }}
                        className="w-[14px] h-[14px] rounded-full bg-primary border-2 border-background shadow-[0_0_10px_hsl(var(--primary)/0.5)]"
                      />
                    </div>

                    {/* Phase card */}
                    <div className="glass-card p-5 sm:p-6 hover:border-primary/30 transition-colors">
                      <div className="flex flex-wrap items-center gap-2 mb-3">
                        <span className="px-2.5 py-0.5 text-xs font-bold rounded-full bg-primary/20 text-primary">
                          {phase.phase || `Phase ${index + 1}`}
                        </span>
                        <span className="flex items-center gap-1 text-xs text-muted-foreground">
                          <Clock className="w-3 h-3" />
                          {phase.duration}
                        </span>
                      </div>

                      <h4 className="text-lg font-bold mb-4">{phase.title}</h4>

                      {/* Skills */}
                      {phase.skills && phase.skills.length > 0 && (
                        <div className="mb-4">
                          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2 flex items-center gap-1.5">
                            <Target className="w-3.5 h-3.5 text-primary" />
                            Skills to Learn
                          </p>
                          <div className="flex flex-wrap gap-1.5">
                            {phase.skills.map((skill) => (
                              <span key={skill} className="px-2.5 py-1 text-xs rounded-md bg-primary/10 text-primary border border-primary/20">
                                {skill}
                              </span>
                            ))}
                          </div>
                        </div>
                      )}

                      {/* Certifications */}
                      {phase.certifications && phase.certifications.length > 0 && (
                        <div className="mb-4">
                          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2 flex items-center gap-1.5">
                            <Award className="w-3.5 h-3.5 text-amber-400" />
                            Certifications
                          </p>
                          <div className="flex flex-wrap gap-1.5">
                            {phase.certifications.map((cert) => (
                              <span key={cert} className="px-2.5 py-1 text-xs rounded-md bg-amber-500/10 text-amber-400 border border-amber-500/20">
                                {cert}
                              </span>
                            ))}
                          </div>
                        </div>
                      )}

                      {/* Projects */}
                      {phase.projects && phase.projects.length > 0 && (
                        <div>
                          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2 flex items-center gap-1.5">
                            <FolderGit2 className="w-3.5 h-3.5 text-emerald-400" />
                            Projects to Build
                          </p>
                          <div className="flex flex-wrap gap-1.5">
                            {phase.projects.map((project) => (
                              <span key={project} className="px-2.5 py-1 text-xs rounded-md bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                                {project}
                              </span>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>
                  </motion.div>
                ))}

                {/* End dot */}
                <div className="relative">
                  <div className="absolute -left-8 sm:-left-12 top-0">
                    <motion.div
                      initial={{ scale: 0 }}
                      animate={{ scale: 1 }}
                      transition={{ delay: 0.8, type: 'spring', stiffness: 300 }}
                      className="w-[14px] h-[14px] rounded-full bg-emerald-400 border-2 border-background shadow-[0_0_10px_hsl(142_71%_45%/0.5)]"
                    />
                  </div>
                  <p className="text-sm font-semibold text-emerald-400">🎯 Goal Achieved — Ready for your target role!</p>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </Layout>
  );
};

export default RoadmapsPage;
